--------------------------------------------------------
--  파일이 생성됨 - 화요일-2월-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOLLOW
--------------------------------------------------------

  CREATE TABLE "FOLLOW" 
   (	"FOLLOW_NO" NUMBER, 
	"FOLLOWER" VARCHAR2(100 BYTE), 
	"FOLLOWEE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FOLLOW"."FOLLOW_NO" IS '팔로우번호';
   COMMENT ON COLUMN "FOLLOW"."FOLLOWER" IS '팔로워';
   COMMENT ON COLUMN "FOLLOW"."FOLLOWEE" IS '팔로위';
   COMMENT ON TABLE "FOLLOW"  IS '팔로우';
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_NICKNAME" VARCHAR2(100 BYTE), 
	"USER_PASSWORD" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_TEL" VARCHAR2(100 BYTE), 
	"USER_BIRTH" DATE, 
	"USER_CLASS" VARCHAR2(200 BYTE), 
	"USER_RATING" NUMBER, 
	"USER_THEME" NUMBER, 
	"USER_SIGN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "USERS"."USER_ID" IS '이메일아이디';
   COMMENT ON COLUMN "USERS"."USER_NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "USERS"."USER_PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "USERS"."USER_NAME" IS '이름';
   COMMENT ON COLUMN "USERS"."USER_TEL" IS '전화번호';
   COMMENT ON COLUMN "USERS"."USER_BIRTH" IS '생일';
   COMMENT ON COLUMN "USERS"."USER_CLASS" IS '학급';
   COMMENT ON COLUMN "USERS"."USER_RATING" IS '등급';
   COMMENT ON COLUMN "USERS"."USER_THEME" IS '테마';
   COMMENT ON COLUMN "USERS"."USER_SIGN_DATE" IS '가입일자';
   COMMENT ON TABLE "USERS"  IS '회원';
REM INSERTING into FOLLOW
SET DEFINE OFF;
Insert into FOLLOW (FOLLOW_NO,FOLLOWER,FOLLOWEE) values (1,'a001','a002');
Insert into FOLLOW (FOLLOW_NO,FOLLOWER,FOLLOWEE) values (2,'a001','a003');
Insert into FOLLOW (FOLLOW_NO,FOLLOWER,FOLLOWEE) values (3,'a002','a004');
REM INSERTING into USERS
SET DEFINE OFF;
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('psh40963@naver.com','테스터쉐인','6KypaPgI1kKDRC6/nus6fg==','박세현','1234',to_date('2005/01/01','RRRR/MM/DD'),'202011_302',1,null,to_date('2021/02/16','RRRR/MM/DD'));
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('chdnjs7610@gmail.com','테스터스칼릿','D63dx0pwD8m458qy5Bx0lg==','박초원','1234',to_date('2005/01/01','RRRR/MM/DD'),'202011_302',1,null,to_date('2021/02/16','RRRR/MM/DD'));
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('a001','지존쉐인','sa/6l8wdhncpYzkFD168Yw==','shane','010-1234-1234',to_date('2001/01/01','RRRR/MM/DD'),'202011_302',1,1,to_date('2021/02/16','RRRR/MM/DD'));
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('a002','나는써머','1234','summer','010-1111-1111',to_date('2002/02/02','RRRR/MM/DD'),'202011_302',1,1,to_date('2021/02/16','RRRR/MM/DD'));
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('a003','최강스칼릿','1234','scarlett','010-2222-2222',to_date('2003/03/03','RRRR/MM/DD'),'202011_302',1,null,to_date('2021/02/16','RRRR/MM/DD'));
Insert into USERS (USER_ID,USER_NICKNAME,USER_PASSWORD,USER_NAME,USER_TEL,USER_BIRTH,USER_CLASS,USER_RATING,USER_THEME,USER_SIGN_DATE) values ('a004','조쉬짱','1234','josh','010-3333-3333',to_date('2004/04/04','RRRR/MM/DD'),'202011_302',1,1,to_date('2021/02/16','RRRR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_FOLLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FOLLOW" ON "FOLLOW" ("FOLLOW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_USERS" ON "USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOLLOW
--------------------------------------------------------

  ALTER TABLE "FOLLOW" MODIFY ("FOLLOW_NO" NOT NULL ENABLE);
  ALTER TABLE "FOLLOW" MODIFY ("FOLLOWER" NOT NULL ENABLE);
  ALTER TABLE "FOLLOW" MODIFY ("FOLLOWEE" NOT NULL ENABLE);
  ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY ("FOLLOW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
